# Generated by Django 6.0.1 on 2026-01-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200, verbose_name="Название")),
                ("value", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "value_ru",
                    models.TextField(blank=True, verbose_name="Описание на русском"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Элемент",
                "verbose_name_plural": "Элементы",
                "ordering": ["-created_at"],
            },
        ),
    ]
