# Generated by Django 5.2.1 on 2026-01-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Задний фон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Задний фон",
                "verbose_name_plural": "Задний фон",
            },
        ),
        migrations.CreateModel(
            name="Doiposle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Время"
                    ),
                ),
                (
                    "mini_description",
                    models.CharField(
                        blank=True,
                        max_length=123,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "first_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Первое изображение",
                    ),
                ),
                (
                    "second_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Второе изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "До и после",
                "verbose_name_plural": "До и после",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Файл"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Тип файла"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Логотип"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Название"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Useproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Время"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Казахстан", "Казахстан"),
                            ("Россия", "Россия"),
                            ("Турция", "Турция"),
                            ("Узбекистан", "Узбекистан"),
                            ("Кыргызстан", "Кыргызстан"),
                            ("Казахстан", "Казахстан"),
                            ("Россия", "Россия"),
                            ("Турция", "Турция"),
                            ("Узбекистан", "Узбекистан"),
                            ("Кыргызстан", "Кыргызстан"),
                            ("Япония", "Япония"),
                            ("Китай", "Китай"),
                            ("Молдова", "Молдова"),
                            ("Грузия", "Грузия"),
                            ("Италия", "Италия"),
                            ("Германия", "Германия"),
                            ("Англия", "Англия"),
                            ("Франция", "Франция"),
                            ("Испания", "Испания"),
                            ("Германия", "Германия"),
                            ("Англия", "Англия"),
                            ("Франция", "Франция"),
                            ("Испания", "Испания"),
                        ],
                        max_length=123,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "mini_description",
                    models.CharField(
                        blank=True,
                        max_length=123,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Изображение"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Преимущества",
                "verbose_name_plural": "Преимущества",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Uslugi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Время"
                    ),
                ),
                (
                    "mini_description",
                    models.CharField(
                        blank=True,
                        max_length=123,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Изображение"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="key",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
    ]
